version: '3.9'

services:
  app:
    image: 'hakanozdmr/todo-api:1.0'
    container_name: todo-api
    ports:
      - 9090:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/todo?autocommit=true
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jpa.hibernate.ddl-auto = update
    restart: "no"
    networks:
      - shared-net

  fe:
    image: 'hakanozdmr/todo-fe:1.0'
    container_name: todo-fe
    ports:
      - 3003:3000
    networks:
      - shared-net
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - shared-net
    volumes:
      - /var/lib/postgresql/data
networks:
  shared-net:
    driver: bridge